### ISSUE TITLE
RPC client not working in Unity WebGL

### ISSUE THREAD

**Issue by hal0x2328** [CityOfZion/NeoModules#12]
In the editor and in the native player, the RPC code works fine to invoke a contract and returns the expected result. But in WebGL I get the following stack trace during the RpcClient.SendAsync call:
```
NeoModules.JsonRpc.Client.RpcClientUnknownException: Error occurred when trying to send rpc requests(s) ---> System.ArgumentNullException: Value cannot be null. UnityLoader.js:1043:37
Parameter name: obj UnityLoader.js:1043:37
  at System.Threading.Monitor.ReliableEnterTimeout (System.Object obj, System.Int32 timeout, System.Boolean& lockTaken) [0x00000] in <00000000000000000000000000000000>:0 UnityLoader.js:1043:37
   --- End of inner exception stack trace --- UnityLoader.js:1043:37
  at NeoModules.JsonRpc.Client.RpcClient+<SendAsync>d__17.MoveNext () [0x00000] in <00000000000000000000000000000000>:0 UnityLoader.js:1043:37
--- End of stack trace from previous location where exception was thrown ---
```
I did some testing and found that the Nethereum RPC client does work in WebGL as long as the AOT version of the Newtonsoft DLL is used, however I have tried that and still receive the error above. I'm unable to pinpoint where the difference lies between the RPC implementation in NeoModules and Nethereum that leads to the error, as the RPC client code doesn't seem all that different.

**Comment by BrunoFreitasgit** [comment]
If I recall correctly, Unity does not support remote async operations, and Nethereum works in Unity because theres is an implementation using Coroutines. I can be wrong, I haven't looked for some time on that repo. Need time to look at this.. Maybe on the weekend I can see what's going on.

**Comment by BrunoFreitasgit** [comment]
Can I close this @hal0x2328 ?

**Comment by hal0x2328** [comment]
> Can I close this @hal0x2328 ?

Yes, unless you want to put in a new issue to get someone to port the Nethereum RPC implementation over. But I think now that there is example code for using either nOS or dAPI APIs with Unity WebGL this may not be really needed.
