### ISSUE TITLE
Parsing error for RPC method getapplicationlog

### ISSUE THREAD

**Issue by vlebedev7** [CityOfZion/NeoModules#14]
I have some problem with the RPC library parsing getapplicationlog result. 

Error and working curl example:
![image](https://user-images.githubusercontent.com/5006907/55422597-cd0e3e80-559d-11e9-9c49-40d21a573eac.png)
As you can see, json parsing throws on path 'executions[0].notifications[0].state.type'

Curl request: 
```
curl -X POST \
    http://localhost:20332 \
    -H 'Content-Type: application/json' \
    -d '{ "jsonrpc": "2.0", "id": 5, "method": "getapplicationlog", "params": ["a5e6a987e36bcc99545cb2b68c1d9dd855ce51eb2e78be4b270299b6f54cb3e0"] }'
```

Curl response:
`{"jsonrpc":"2.0","id":5,"result":{"txid":"0x8fdc250403ecabda4a5d204fe5f1f3596533be5a6eefd1c2c73d123961d846a2","executions":[{"trigger":"Application","contract":"0xef95a5008fe8bd2a28673a1cb49559a7d7d860f2","vmstate":"HALT, BREAK","gas_consumed":"8.879","stack":[{"type":"Integer","value":"1"}],"notifications":[{"contract":"0xfde69a7dd2a1c948977fb3ce512158987c0e2197","state":{"type":"Array","value":[{"type":"ByteArray","value":"6f7261636c654f70657261746f72"},{"type":"ByteArray","value":"6d8603dc755b733aa10f0bb96585c8bed967ce1b"},{"type":"ByteArray","value":"736e656f5f7072696365"},{"type":"ByteArray","value":""},{"type":"ByteArray","value":"78ea9741"},{"type":"Integer","value":"2"}]}},{"contract":"0xfde69a7dd2a1c948977fb3ce512158987c0e2197","state":{"type":"Array","value":[{"type":"ByteArray","value":"6f7261636c654f70657261746f72"},{"type":"ByteArray","value":"6d8603dc755b733aa10f0bb96585c8bed967ce1b"},{"type":"ByteArray","value":"736e656f5f7072696365"},{"type":"ByteArray","value":""},{"type":"Integer","value":"1094979175"},{"type":"Integer","value":"5"}]}}]}]}}`

neo cli version 2.9.4
C# packages: 
```
<PackageReference Include="NeoModules.Rest" Version="2.0.0" />
<PackageReference Include="NeoModules.RPC" Version="1.2.0" />
```

**Comment by BrunoFreitasgit** [comment]
Fixed in https://github.com/CityOfZion/NeoModules/commit/482b9f50d6ac87ae82e37593aaef6679274e2315

**Comment by vlebedev7** [comment]
Now it works fine, thanks!
