### ISSUE TITLE
Nuget version is not the same of the code

### ISSUE THREAD

**Issue by aboimpinto** [CityOfZion/NeoModules#6]
Trying to use the Nuget package and in the object AccountSignerTransactionManager there is no CallContract but there is in the code.

When you expect to have a new Nuget version?

**Comment by BrunoFreitasgit** [comment]
New NuGet versions are now available at https://www.nuget.org/profiles/BrunoFreitas, sorry for the inconvenience.

**Comment by IprelProgetti** [comment]
Hi @BrunoFreitasgit ,
I just run into 

> MissingMethodException: Method not found: 'System.Decimal NeoModules.Rest.DTOs.NeoScan.Unspent.get_Value()' 

after I called the `DeployContract()` method. I installed all the last NuGet packages available. 
Is it normal that the `Value` getter isn't found?
