### ISSUE TITLE
ScriptHash return a strange error

### ISSUE THREAD

**Issue by aboimpinto** [CityOfZion/NeoModules#7]
When I deploy a smart contract in the blockchain using NeoGui i get the script hash: 
0xf79edf718d2bb58d3eba9975e1d5b4c9feb21a69

then I try to execute the CallContract using this hash I get BatFormat Exception.

I notice in the example the Script Hash that you have are a little bit different:
// contract 
public const string ContractScriptHash = "ed07cffad18f1308db51920d99a2af60ac66a7b3";

where do you calculate this Contract script hash?????

**Comment by BrunoFreitasgit** [comment]
This is fixed in https://github.com/CityOfZion/NeoModules/commit/ee8c774591e9e862ff4f767efdc3f096e46bd76f
